### PR TITLE
Fixed errors and glitchy ending

### PR DESCRIPTION
**Pull request by PatatjeMC**
I fixed 2 common errors and changed something so the ending doesn't freeze for a second

### CODE REVIEW

**Comment by mrawesomey** [comment]
So I tried this and all the comments which are going to be used for the video are written in cmd so it is irritating but the bugs are gone

**Comment by PatatjeMC** [comment]
Did you manually apply the code if so you probably forgot to delete the print functions in the main.py they where already there but that function was implemented incorrectly never triggering them

**Comment by mrawesomey** [comment]
What where?

**Comment by PatatjeMC** [comment]
image

**Comment by PatatjeMC** [comment]
image

**Comment by PatatjeMC** [comment]
I have noticed 1 more error that I'm working on fixing so don't merge this pull request

**Comment by JasonLovesDoggo** [comment]
Gotcha

**Comment by PatatjeMC** [comment]
All the errors I could find are fixed

**Comment by JasonLovesDoggo** [comment]
Ready to merge?

**Comment by PatatjeMC** [comment]
Yes

**Comment by JasonLovesDoggo** [comment]
Everything looks good to me so!

**Pull request merged**
