### PR TITLE
A few fixes and better audio

### PR DESCRIPTION
**Pull request by PatatjeMC**
btw sorry for the so many commits I forgot to merge upstream a few times and then they became unmergable because of my changes so I had to revert the commits and then redo them after merging (I'm not that experienced with git other then private repository's) idk what happened with the typing module but typings isn't a thing I can install using pip or find anywhere and it's giving errors that it doesn't exist and it doesn't with typing so I hope it's the same module but it works I guess.

### CODE REVIEW

**Comment by JasonLovesDoggo** [comment]
Typings is installed by default you don't have to install it with PIP

**Comment by JasonLovesDoggo** [comment]
I will merge this later, I just want to be able to test Right away in case it breaks or something

**Comment by JasonLovesDoggo** [comment]
hey @PatatjeMC 
```
Input formats were only specified for 0 out of 2 files.The last 2 files will remain unformatted.
unable to validate file formats.
Saving...                                            1% -:--:--
Traceback (most recent call last):
  File "C:\Users\Jason\os-contribs\RedditVideoMakerBot\main.py", line 62, in <module>
    main()
  File "C:\Users\Jason\os-contribs\RedditVideoMakerBot\main.py", line 40, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\Jason\os-contribs\RedditVideoMakerBot\video_creation\voices.py", line 51, in save_text_to_mp3
    ttttsw.tts(
  File "C:\Users\Jason\os-contribs\RedditVideoMakerBot\video_creation\TTSwrapper.py", line 121, in tts
    cbn.build(audio_clips, filename, "concatenate")
  File "C:\Users\Jason\WebstormProjects\complete website\RedditVideoMakerBot\lib\site-packages\sox\combine.py", line 105, in build
    raise SoxError(
sox.core.SoxError: Stdout: 
Stderr: sox FAIL util: Unable to load MAD decoder library (libmad).
sox FAIL formats: can't open input file `assets/temp/mp3/1-1.mp3': 

```

**Comment by PatatjeMC** [comment]
Ohw it requires a few dll files on windows but I use linux and had the package installed for it I'll add something to automatically set it up later

**Pull request merged**
